# Generated by Django 5.0.7 on 2026-08-18 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('time', models.TimeField(verbose_name='Vaqt')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Murojaat sababi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Navbat',
                'verbose_name_plural': 'Navbatlar',
                'ordering': ['-date', '-time'],
                'unique_together': {('doctor', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tahlil nomi')),
                ('file', models.FileField(upload_to='lab_results/', verbose_name='Fayl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laboratoriya natijasi',
                'verbose_name_plural': 'Laboratoriya natijalari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Tashxis')),
                ('prescription', models.TextField(blank=True, verbose_name='Retsept / tavsiyalar')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Tibbiy karta yozuvi',
                'verbose_name_plural': 'Tibbiy karta yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
