# Generated by Django 5.0.7 on 2026-08-18 04:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('icon', models.CharField(default='bi-heart-pulse', help_text='Bootstrap Icons nomi, masalan: bi-heart-pulse', max_length=50)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=150, verbose_name='Mutaxassislik')),
                ('bio', models.TextField(blank=True, verbose_name='Tavsif / tarjimai hol')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Ish tajribasi (yil)')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name="Qabul narxi (so'm)")),
                ('schedule', models.CharField(blank=True, help_text='Masalan: Dush-Juma, 09:00-17:00', max_length=255, verbose_name='Ish jadvali')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Xona raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.department', verbose_name="Bo'lim")),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shifokor profili',
                'verbose_name_plural': 'Shifokor profillari',
                'ordering': ['-experience_years'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, verbose_name='Sharh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
